version: '3.8'

services:
  db:
    container_name: db
    hostname: db
    image: library/postgres:14.1

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - eat_place_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test_db:
    container_name: test_db
    hostname: test_db
    image: library/postgres:14.1

    environment:
      - POSTGRES_USER=rest
      - POSTGRES_PASSWORD=rest
      - POSTGRES_DB=rest
    volumes:
      - eat_place_test_pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: redis
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - 6379:6379


  rest_api:
    image: timofeytst/eat-place:rest_api_dev
    ports:
      - "8000:8000"
    restart: always
    
    env_file:
      - .env
    depends_on:
      - db
      - redis

  web_ui:
    image: timofeytst/eat-place:web_ui_dev
    ports:
      - "3000:3000"
    restart: always      
    environment:
      REACT_APP_DEV: dev
    depends_on:
      - rest_api

volumes:
  eat_place_pg_data:
    driver: "local"

  eat_place_test_pg_data:
    driver: "local"

networks:
  default:
    external: true
    name: eat_place
