version: '3.8'

services:

  web-ui:
    image: timofeytst/eat_place:web_ui_prod
    ports:
      - "3000:80"
    restart: always      
    environment:
      REACT_APP_DEV: prod

  db:
    container_name: db
    hostname: db
    image: library/postgres:14.1

    environment:
      - POSTGRES_USER=rest
      - POSTGRES_PASSWORD=rest
      - POSTGRES_DB=rest
    volumes:
      - eat_place_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - 6379:6379

volumes:
  eat_place_pg_data:
    driver: "local"

networks:
  default:
    external: true
    name: eat_place
