version: '3.8'

services:
  db:
    container_name: db
    hostname: db
    image: library/postgres:14.1

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - eat_place_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: redis
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379


  rest_api:
    image: timofeytst/eat-place:rest_api_prod
    ports:
      - "9000:9000"
    restart: always
    
    env_file:
      - .prod.env
    depends_on:
      - db
      - redis

  web_ui:
    image: timofeytst/eat-place:web_ui_prod
    ports:
      - "3000:80"
    restart: always      
    environment:
      REACT_APP_DEV: prod
    depends_on:
      - rest_api

volumes:
  eat_place_pg_data:
    driver: "local"

networks:
  default:
    external: true
    name: eat_place
